# Generated by Django 6.0.5 on 2026-05-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('imagen', models.ImageField(null=True, upload_to='imgs/', verbose_name='Imagen')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
    ]
